### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by davidgg** [MarsBased/handbook#45]
I think we should add a 'Contributing' section to the README file. You already know, but something like describing the flow (be a ~martian, fork the repository, make changes, create a PR, wait until devs vote ...), describe the content of the PR, etc.

Do we should open an issue before creating a PR?

**Comment by xredo** [comment]
Based on what you said, I would add the _Contributing guide_ in the README and a _PR template_.

As for the flow, I wouldn't enforce someone to open an issue before opening a PR. Issues will be used as questions, discussions, suggestions, pointing out fixes, etc.

But if it's easier to make the change than to explain what change do you want to make I believe that it's better to open the PR with the change.

**Comment by davidgg** [comment]
@xredo Great, I'll draft a PR
